### ISSUE TITLE
Unable to do assertions for the number -4

### ISSUE THREAD

**Issue by bfrymire** [Emperor2000/gml-min-assert#1]
In each of the assertion scripts, there's a check to see if the expected and actual values are defined and valid. When testing if -4 is a negative value, it will incorrectly throw an error that the parameter is not correctly defined.

For example:

`
AssertNegative("This will throw an error despite being a valid assertion.", -4);
`

**Comment by Emperor2000** [comment]
Thanks for opening an issue, working on a fix! @bfrymire

**Comment by bfrymire** [comment]
The keyword `noone` and `-4` are equal during run time. This unfortunately makes the merged solution not work.
I wish YoYo would make `noone` a true datatype or remove it entirely.

**Comment by Emperor2000** [comment]
> The keyword `noone` and `-4` are equal during run time. This unfortunately makes the merged solution not work.
> I wish YoYo would make `noone` a true datatype or remove it entirely.

Ah that's a shame, I was "sure" that that wouldn't be an issue but I stand corrected. 
In that case the only solution I can think of right now is to just stop checking it for the moment, the undefined check will have to do, and in that case I'm just going to hope people don't send objects in the params that haven't been created yet, ill look at a better solution in the meantime.

I'll be sure to at least deal with it this way the next version. I want to make some time this week to close all issues posted thus far (most of which are enhancements).

**Comment by Emperor2000** [comment]
Hey thank you again for reporting this issue. I have been incredibly busy the last year but I took some time to look at this issue. 
As noone and -4 are equal during runtime there seems to be no reliable way to give an exception when a value is noone. Instead a warning will now be shown when a user checks -4, mentioning that it can also be equal to noone during runtime.

At this time this seems to be the best solution or mitigation to the issue.
